/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmmInput {
        "allowClear": boolean;
        "bordered": boolean;
        "defaultValue": string;
        "disabled": boolean;
        "maxLength": number | undefined;
        "size": 'large' | 'middle' | 'small' | undefined;
        "type": string | undefined;
        "value": string | undefined;
    }
}
declare global {
    interface HTMLEmmInputElement extends Components.EmmInput, HTMLStencilElement {
    }
    var HTMLEmmInputElement: {
        prototype: HTMLEmmInputElement;
        new (): HTMLEmmInputElement;
    };
    interface HTMLElementTagNameMap {
        "emm-input": HTMLEmmInputElement;
    }
}
declare namespace LocalJSX {
    interface EmmInput {
        "allowClear"?: boolean;
        "bordered"?: boolean;
        "defaultValue"?: string;
        "disabled"?: boolean;
        "maxLength"?: number | undefined;
        "onPressEnter"?: (event: CustomEvent<EmmInput>) => void;
        "size"?: 'large' | 'middle' | 'small' | undefined;
        "type"?: string | undefined;
        "value"?: string | undefined;
    }
    interface IntrinsicElements {
        "emm-input": EmmInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emm-input": LocalJSX.EmmInput & JSXBase.HTMLAttributes<HTMLEmmInputElement>;
        }
    }
}
