/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmmInput {
    }
}
declare global {
    interface HTMLEmmInputElement extends Components.EmmInput, HTMLStencilElement {
    }
    var HTMLEmmInputElement: {
        prototype: HTMLEmmInputElement;
        new (): HTMLEmmInputElement;
    };
    interface HTMLElementTagNameMap {
        "emm-input": HTMLEmmInputElement;
    }
}
declare namespace LocalJSX {
    interface EmmInput {
    }
    interface IntrinsicElements {
        "emm-input": EmmInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emm-input": LocalJSX.EmmInput & JSXBase.HTMLAttributes<HTMLEmmInputElement>;
        }
    }
}
